### PR TITLE
ddfssfds

### PR DESCRIPTION
**Pull request by fernandorubbo**

### CODE REVIEW

**Comment by fernandorubbo** [comment]
$BODY

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) |    DELTA (USD)    |
|-----------------------|-----------------------|-----------------------|-------------------|-------------------|
| PersistentVolumeClaim | wordpress-volumeclaim |                 36.00 |             36.00 |                   |
| SQLInstance           | sqldb                 |                 97.27 |            194.54 | +97.27 (&#8593;)  |
| Deployment            | wordpress             |                 44.03 |            110.08 | +66.05 (&#8593;)  |
| Service               | wordpress             |                 21.00 |             21.00 |                   |
|                       | TOTAL                 |                198.31 |            361.63 | +163.32 (&#8593;) |


This PR increases the infrastructure cost by *$163.32 per month* (&#8593;).

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) | DELTA (USD) |
|-----------------------|-----------------------|-----------------------|-------------------|-------------|
| PersistentVolumeClaim | wordpress-volumeclaim |                  0.00 |              0.00 |             |
| SQLInstance           | sqldb                 |                  0.00 |              0.00 |             |
| Service               | wordpress             |                 21.00 |             21.00 |             |
|                       | TOTAL                 |                 21.00 |             21.00 |             |

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) | DELTA (USD) |
|-----------------------|-----------------------|-----------------------|-------------------|-------------|
| SQLInstance           | sqldb                 |                  0.00 |              0.00 |             |
| Service               | wordpress             |                 21.00 |             21.00 |             |
| PersistentVolumeClaim | wordpress-volumeclaim |                  0.00 |              0.00 |             |
|                       | TOTAL                 |                 21.00 |             21.00 |             |

**Review by fbrubbo — APPROVED** [review]
LGTM

**Pull request merged**
