### PR TITLE
increase replicas

### PR DESCRIPTION
**Pull request by fernandorubbo**

### CODE REVIEW

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) | DELTA (USD) |
|-----------------------|-----------------------|-----------------------|-------------------|-------------|
| SQLInstance           | sqldb                 |                  0.00 |              0.00 |             |
| Service               | wordpress             |                 21.00 |             21.00 |             |
| PersistentVolumeClaim | wordpress-volumeclaim |                  0.00 |              0.00 |             |
|                       | TOTAL                 |                 21.00 |             21.00 |             |

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) | DELTA (USD) |
|-----------------------|-----------------------|-----------------------|-------------------|-------------|
| PersistentVolumeClaim | wordpress-volumeclaim |                  0.00 |              0.00 |             |
| SQLInstance           | sqldb                 |                  0.00 |              0.00 |             |
| Service               | wordpress             |                 21.00 |             21.00 |             |
|                       | TOTAL                 |                 21.00 |             21.00 |             |

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) | DELTA (USD) |
|-----------------------|-----------------------|-----------------------|-------------------|-------------|
| Service               | wordpress             |                 21.00 |             21.00 |             |
| PersistentVolumeClaim | wordpress-volumeclaim |                  0.00 |              0.00 |             |
| SQLInstance           | sqldb                 |                  0.00 |              0.00 |             |
|                       | TOTAL                 |                 21.00 |             21.00 |             |

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) | DELTA (USD) |
|-----------------------|-----------------------|-----------------------|-------------------|-------------|
| SQLInstance           | sqldb                 |                  0.00 |              0.00 |             |
| Service               | wordpress             |                 21.00 |             21.00 |             |
| PersistentVolumeClaim | wordpress-volumeclaim |                  0.00 |              0.00 |             |
|                       | TOTAL                 |                 21.00 |             21.00 |             |

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) |   DELTA (USD)    |
|-----------------------|-----------------------|-----------------------|-------------------|------------------|
| SQLInstance           | sqldb                 |                194.54 |            194.54 |                  |
| Deployment            | wordpress             |                154.12 |            220.17 | +66.05 (&#8593;) |
| Service               | wordpress             |                 21.00 |             21.00 |                  |
| PersistentVolumeClaim | wordpress-volumeclaim |                 36.00 |             36.00 |                  |
|                       | TOTAL                 |                405.66 |            471.71 | +66.05 (&#8593;) |


This PR increases the infrastructure cost by *$66.05 per month* (&#8593;).

**Comment by fernandorubbo** [comment]
Infrastructure Cost Estimate
--------------

|     RESOURCE TYPE     |         NAME          | CURRENT MONTHLY (USD) | NEW MONTHLY (USD) |   DELTA (USD)    |
|-----------------------|-----------------------|-----------------------|-------------------|------------------|
| Deployment            | wordpress             |                154.12 |            220.17 | +66.05 (&#8593;) |
| Service               | wordpress             |                 21.00 |             21.00 |                  |
| PersistentVolumeClaim | wordpress-volumeclaim |                 36.00 |             36.00 |                  |
| SQLInstance           | sqldb                 |                194.54 |            194.54 |                  |
|                       | TOTAL                 |                405.66 |            471.71 | +66.05 (&#8593;) |


This PR increases the infrastructure cost by *$66.05 per month* (&#8593;).

**Review by fbrubbo — COMMENTED** [review]
LGTM

**Review by fbrubbo — APPROVED** [review]

**Pull request merged**
